# Generated by Django 3.1.5 on 2021-12-14 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20211213_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_datetime',
            new_name='timestamp',
        ),
    ]
