# Generated by Django 3.1.5 on 2021-12-14 20:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20211213_2050'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, follower_user=django.db.models.expressions.F('follows_user')), name='not_follow_self'),
        ),
    ]
